#!/bin/bash

CWD=$(cd $(dirname $0) && pwd)

MODE=$1

if [ "${MODE}" = "-s" ]; then
  :
elif [ "${MODE}" = "-r" ]; then
  :
else
  echo "usage: $0 -s [prefix]"
  echo "       $0 -r [prefix]"
fi

PREFIX=.
if [ -n "$2" ]; then
  PREFIX=$2
fi
STORE_FILENAME=.store-link_${PREFIX}

NODE_DIR=${PREFIX}/node_modules

if [ ! -d "${NODE_DIR}" ]; then
  exit 0
fi

store() {
  ABS_BIN_DIR=$(npm bin --prefix=${PREFIX})
  BIN_DIR=${ABS_BIN_DIR#${CWD}/}
  COMMANDS=$(npm bin --prefix=${PREFIX} | xargs ls)

  echo ${BIN_DIR} > ${STORE_FILENAME}
  for link in $COMMANDS; do
    echo "${link} $(readlink ${ABS_BIN_DIR}/${link})" >> ${STORE_FILENAME}
  done
}

restore() {
  if [ ! -f "${STORE_FILENAME}" ]; then
    echo ${STORE_FILENAME} is not found.
    exit 1
  fi

  BIN_DIR=$(cat ${STORE_FILENAME} | head -n 1)
  rm -rf ${BIN_DIR}
  mkdir -p ${BIN_DIR}

  IFS=' '
  while read line; do
    if [ ! "${BIN_DIR}" = "${line}" ]; then
      set -- $line
      target=$1
      src=$2
      #echo $target $src
      ln -s ${src#${BIN_DIR}/} ${BIN_DIR}/$target
    fi
  done < ${STORE_FILENAME}
}

if [ "${MODE}" = "-s" ]; then
  store
fi

if [ "${MODE}" = "-r" ]; then
  restore
fi

#vim:ft=sh
