#!/bin/bash

CWD=$(cd $(dirname $0) && pwd)

MODE=$1

if [ "${MODE}" = "-s" ]; then
  :
elif [ "${MODE}" = "-r" ]; then
  :
else
  echo "usage: $0 -s [prefix]"
  echo "       $0 -r [prefix]"
fi

PREFIX=.
TARGET_DIR=${CWD}
if [ -n "$2" ]; then
  PREFIX=$2
  TARGET_DIR=${CWD}/${PREFIX}
fi
STORE_FILENAME=${TARGET_DIR}/.store-link

store() {
  COMMANDS=$(ls ${TARGET_DIR})
  echo ${TARGET_DIR} > ${STORE_FILENAME}
  for file in $COMMANDS; do
    link=$(readlink ${TARGET_DIR}/${file})
    if [ -n "${link}" ]; then
      echo "${file} ${link}" >> ${STORE_FILENAME}
    fi
  done
}

restore() {
  if [ ! -f "${STORE_FILENAME}" ]; then
    echo ${STORE_FILENAME} is not found.
    exit 1
  fi
  TARGET_DIR=$(cat ${STORE_FILENAME} | head -n 1)
  IFS=' '
  while read line; do
    if [ ! "${TARGET_DIR}" = "${line}" ]; then
      set -- $line
      target=${TARGET_DIR}/$1
      src=$2
      rm -f ${target}
      ln -s ${src#${TARGET_DIR}/} ${target}
    fi
  done < ${STORE_FILENAME}
}

if [ "${MODE}" = "-s" ]; then
  store
fi

if [ "${MODE}" = "-r" ]; then
  restore
fi

#vim:ft=sh
